### ISSUE TITLE
name of merged dataset

### ISSUE THREAD

**Issue by AnnikaNoren** [learn-co-curriculum/dsc-obtaining-your-data-lab#2]
The last block of code in the answer key uses the file name "lego_data_merged.csv" - where in the process was that created?  In the SQL query the database with all the join statements the dataframe is called "df".  How was the leap made from "df" to "lego_data_merged.csv"?

Last cell of code in answer key:
df.to_csv('Lego_data_merged.csv', index=False)

**Comment by hoffm386** [comment]
Hi @AnnikaNoren, that part of the code means that we are taking a variable in memory (`df`) and writing its contents to a CSV file (`Lego_data_merged.csv`). The file is automatically created when that line of code is executed.

I'm going to go ahead and close out this issue.
